# Generated by Django 3.0.5 on 2020-10-07 10:02

from django.db import migrations, models
import djongo.models.fields
import visualisations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('info', djongo.models.fields.ArrayField(model_container=visualisations.models.Info)),
            ],
        ),
    ]
