# Generated by Django 3.0.5 on 2020-10-17 07:12

from django.db import migrations, models
import djongo.models.fields
import visualisations.models


class Migration(migrations.Migration):

    dependencies = [
        ('visualisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('aggregated_returns', djongo.models.fields.ArrayField(model_container=visualisations.models.AggregatedYearlyReturns)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('industry', models.CharField(max_length=50)),
                ('financials', djongo.models.fields.ArrayField(model_container=visualisations.models.IncomeStatement)),
                ('balance_sheet', djongo.models.fields.ArrayField(model_container=visualisations.models.BalanceSheet)),
                ('cash_flow', djongo.models.fields.ArrayField(model_container=visualisations.models.CashFlow)),
            ],
        ),
    ]
